"""empty message

Revision ID: 067a780087c5
Revises: 2a8d6b8c5431
Create Date: 2021-09-11 15:20:40.448199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '067a780087c5'
down_revision = '2a8d6b8c5431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'merchants', ['short_code'])
    op.add_column('merchants_condition_multiplier', sa.Column('merchant', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'merchants_condition_multiplier', 'merchants', ['merchant'], ['short_code'])
    op.drop_column('merchants_condition_multiplier', 'merchant_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants_condition_multiplier', sa.Column('merchant_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'merchants_condition_multiplier', type_='foreignkey')
    op.drop_column('merchants_condition_multiplier', 'merchant')
    op.drop_constraint(None, 'merchants', type_='unique')
    # ### end Alembic commands ###
