"""empty message

Revision ID: 0885d01cb642
Revises: 6cbef060159f
Create Date: 2021-08-20 11:20:42.485355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0885d01cb642'
down_revision = '6cbef060159f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('scryfall_card_id', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('lang', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('name', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('uri', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('scryfall_uri', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('cmc', sa.Float(), nullable=True))
    op.add_column('cards', sa.Column('cardmarket_id', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('color_identity', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('colors', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('keywords', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('foil', sa.Boolean(), nullable=True))
    op.add_column('cards', sa.Column('nonfoil', sa.Boolean(), nullable=True))
    op.add_column('cards', sa.Column('etchedfoil', sa.Boolean(), nullable=True))
    op.add_column('cards', sa.Column('mana_cost', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('oracle_text', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('power', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('reserved', sa.Boolean(), nullable=True))
    op.add_column('cards', sa.Column('toughness', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('type_line', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('artist', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('booster', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('border_color', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('collector_number', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('flavor_name', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('flavor_text', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('frame', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('image_uris', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('printed_name', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('printed_text', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('printed_type_line', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('illustration_id', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('promo', sa.Boolean(), nullable=True))
    op.add_column('cards', sa.Column('purchase_uris', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('released_at', sa.Date(), nullable=True))
    op.add_column('cards', sa.Column('scryfall_set_uri', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('set_name', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('set_search_uri', sa.Boolean(), nullable=True))
    op.add_column('cards', sa.Column('set_type', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('set_uri', sa.Date(), nullable=True))
    op.add_column('cards', sa.Column('set', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('scryfall_set_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'cards', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cards', type_='unique')
    op.drop_column('cards', 'scryfall_set_id')
    op.drop_column('cards', 'set')
    op.drop_column('cards', 'set_uri')
    op.drop_column('cards', 'set_type')
    op.drop_column('cards', 'set_search_uri')
    op.drop_column('cards', 'set_name')
    op.drop_column('cards', 'scryfall_set_uri')
    op.drop_column('cards', 'released_at')
    op.drop_column('cards', 'purchase_uris')
    op.drop_column('cards', 'promo')
    op.drop_column('cards', 'illustration_id')
    op.drop_column('cards', 'printed_type_line')
    op.drop_column('cards', 'printed_text')
    op.drop_column('cards', 'printed_name')
    op.drop_column('cards', 'image_uris')
    op.drop_column('cards', 'frame')
    op.drop_column('cards', 'flavor_text')
    op.drop_column('cards', 'flavor_name')
    op.drop_column('cards', 'collector_number')
    op.drop_column('cards', 'border_color')
    op.drop_column('cards', 'booster')
    op.drop_column('cards', 'artist')
    op.drop_column('cards', 'type_line')
    op.drop_column('cards', 'toughness')
    op.drop_column('cards', 'reserved')
    op.drop_column('cards', 'power')
    op.drop_column('cards', 'oracle_text')
    op.drop_column('cards', 'mana_cost')
    op.drop_column('cards', 'etchedfoil')
    op.drop_column('cards', 'nonfoil')
    op.drop_column('cards', 'foil')
    op.drop_column('cards', 'keywords')
    op.drop_column('cards', 'colors')
    op.drop_column('cards', 'color_identity')
    op.drop_column('cards', 'cardmarket_id')
    op.drop_column('cards', 'cmc')
    op.drop_column('cards', 'scryfall_uri')
    op.drop_column('cards', 'uri')
    op.drop_column('cards', 'name')
    op.drop_column('cards', 'lang')
    op.drop_column('cards', 'scryfall_card_id')
    # ### end Alembic commands ###
