"""empty message

Revision ID: 0b9b92e63184
Revises: 1eadea63e8f3
Create Date: 2021-09-24 21:26:47.771706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b9b92e63184'
down_revision = '1eadea63e8f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('label', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'media', ['database_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media', type_='unique')
    op.drop_column('media', 'label')
    # ### end Alembic commands ###
