"""empty message

Revision ID: 0c0855f9d8a6
Revises: 9194dc67f080
Create Date: 2021-12-14 10:38:58.330880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c0855f9d8a6'
down_revision = '9194dc67f080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_lists')
    op.drop_table('user_list_items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_list_items',
    sa.Column('database_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('real_item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_list_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['real_item_id'], ['real_items.database_id'], name='user_list_items_real_item_id_fkey'),
    sa.ForeignKeyConstraint(['user_list_id'], ['user_lists.database_id'], name='user_list_items_user_list_id_fkey'),
    sa.PrimaryKeyConstraint('database_id', name='user_list_items_pkey')
    )
    op.create_table('user_lists',
    sa.Column('database_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date_created', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('date_updated', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('owner', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['users.database_id'], name='user_lists_owner_fkey'),
    sa.PrimaryKeyConstraint('database_id', name='user_lists_pkey')
    )
    # ### end Alembic commands ###
