"""empty message

Revision ID: 0cf3daa4fb41
Revises: 24d10322d366
Create Date: 2021-09-11 15:14:36.223231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cf3daa4fb41'
down_revision = '24d10322d366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('merchants', 'database_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('merchants', 'short_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('merchants_database_id_key', 'merchants', type_='unique')
    op.create_unique_constraint(None, 'merchants', ['short_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'merchants', type_='unique')
    op.create_unique_constraint('merchants_database_id_key', 'merchants', ['database_id'])
    op.alter_column('merchants', 'short_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('merchants', 'database_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
