"""empty message

Revision ID: 0dacc95d1d08
Revises: f5d630d64abf
Create Date: 2021-08-23 22:57:54.436537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dacc95d1d08'
down_revision = 'f5d630d64abf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'conditions', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conditions', type_='unique')
    # ### end Alembic commands ###
