"""empty message

Revision ID: 0ed1b9e19bb5
Revises: fc02b51ddd04
Create Date: 2022-01-11 16:12:41.758584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ed1b9e19bb5'
down_revision = 'fc02b51ddd04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generic_items', sa.Column('item_hash', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'item_lists', ['database_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item_lists', type_='unique')
    op.drop_column('generic_items', 'item_hash')
    # ### end Alembic commands ###
