"""empty message

Revision ID: 0f2da3392995
Revises: cd9b7bb679ef
Create Date: 2021-09-11 12:33:56.287831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f2da3392995'
down_revision = 'cd9b7bb679ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers_history', sa.Column('condition_string', sa.String(), nullable=True))
    op.drop_column('offers_history', 'condition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers_history', sa.Column('condition', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('offers_history', 'condition_string')
    # ### end Alembic commands ###
