"""empty message

Revision ID: 129d7e917888
Revises: 6c29b87dcd4a
Create Date: 2021-09-12 10:07:19.914477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '129d7e917888'
down_revision = '6c29b87dcd4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conditions', 'database_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('conditions', 'us_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('conditions_database_id_key', 'conditions', type_='unique')
    op.create_unique_constraint(None, 'conditions', ['us_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conditions', type_='unique')
    op.create_unique_constraint('conditions_database_id_key', 'conditions', ['database_id'])
    op.alter_column('conditions', 'us_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('conditions', 'database_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
