"""empty message

Revision ID: 1675413e767f
Revises: 9cb1056e20ef
Create Date: 2021-09-24 21:43:47.840906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1675413e767f'
down_revision = '9cb1056e20ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('real_items', sa.Column('creator', sa.Integer(), nullable=True))
    op.add_column('real_items', sa.Column('owner', sa.Integer(), nullable=True))
    op.add_column('real_items', sa.Column('condition', sa.String(), nullable=True))
    op.add_column('real_items', sa.Column('cost_basis', sa.Float(), nullable=True))
    op.add_column('real_items', sa.Column('fmv', sa.Float(), nullable=True))
    op.add_column('real_items', sa.Column('trade_in_value', sa.Float(), nullable=True))
    op.add_column('real_items', sa.Column('woocommerce_url', sa.String(), nullable=True))
    op.add_column('real_items', sa.Column('woocommerce_product_id', sa.Integer(), nullable=True))
    op.add_column('real_items', sa.Column('defect_inked', sa.Boolean(), nullable=True))
    op.add_column('real_items', sa.Column('defect_signed', sa.Boolean(), nullable=True))
    op.add_column('real_items', sa.Column('defect_bend', sa.Boolean(), nullable=True))
    op.add_column('real_items', sa.Column('defect_crease', sa.Boolean(), nullable=True))
    op.add_column('real_items', sa.Column('defect_smudges', sa.Boolean(), nullable=True))
    op.add_column('real_items', sa.Column('defect_curled', sa.Boolean(), nullable=True))
    op.drop_constraint('real_items_user_id_fkey', 'real_items', type_='foreignkey')
    op.create_foreign_key(None, 'real_items', 'conditions', ['condition'], ['us_code'])
    op.create_foreign_key(None, 'real_items', 'users', ['owner'], ['database_id'])
    op.create_foreign_key(None, 'real_items', 'users', ['creator'], ['database_id'])
    op.drop_column('real_items', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('real_items', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'real_items', type_='foreignkey')
    op.drop_constraint(None, 'real_items', type_='foreignkey')
    op.drop_constraint(None, 'real_items', type_='foreignkey')
    op.create_foreign_key('real_items_user_id_fkey', 'real_items', 'users', ['user_id'], ['database_id'])
    op.drop_column('real_items', 'defect_curled')
    op.drop_column('real_items', 'defect_smudges')
    op.drop_column('real_items', 'defect_crease')
    op.drop_column('real_items', 'defect_bend')
    op.drop_column('real_items', 'defect_signed')
    op.drop_column('real_items', 'defect_inked')
    op.drop_column('real_items', 'woocommerce_product_id')
    op.drop_column('real_items', 'woocommerce_url')
    op.drop_column('real_items', 'trade_in_value')
    op.drop_column('real_items', 'fmv')
    op.drop_column('real_items', 'cost_basis')
    op.drop_column('real_items', 'condition')
    op.drop_column('real_items', 'owner')
    op.drop_column('real_items', 'creator')
    # ### end Alembic commands ###
