"""empty message

Revision ID: 1a82639c87ee
Revises: 242958a02bdc
Create Date: 2021-08-22 15:33:14.755996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a82639c87ee'
down_revision = '242958a02bdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('offers_history_item_index_key', 'offers_history', type_='unique')
    op.drop_column('offers_history', 'item_index')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers_history', sa.Column('item_index', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('offers_history_item_index_key', 'offers_history', ['item_index'])
    # ### end Alembic commands ###
