"""empty message

Revision ID: 1ac58a1af63f
Revises: b5f93e2e5ec8
Create Date: 2021-08-23 13:25:30.388535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ac58a1af63f'
down_revision = 'b5f93e2e5ec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers_history', sa.Column('offer', sa.Integer(), nullable=False))
    op.drop_constraint('offers_history_offer_id_fkey', 'offers_history', type_='foreignkey')
    op.create_foreign_key(None, 'offers_history', 'offers', ['offer'], ['id'])
    op.drop_column('offers_history', 'offer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers_history', sa.Column('offer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'offers_history', type_='foreignkey')
    op.create_foreign_key('offers_history_offer_id_fkey', 'offers_history', 'offers', ['offer_id'], ['id'])
    op.drop_column('offers_history', 'offer')
    # ### end Alembic commands ###
