"""empty message

Revision ID: 1ce9a7982fc9
Revises: 6eb2c0ff938b
Create Date: 2021-08-23 13:44:22.515217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ce9a7982fc9'
down_revision = '6eb2c0ff938b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'items', ['id'])
    op.add_column('offers', sa.Column('offer_item_index', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'offers', ['id'])
    op.drop_constraint('offers_item_indexes_fkey', 'offers', type_='foreignkey')
    op.create_foreign_key(None, 'offers', 'items', ['offer_item_index'], ['item_index'])
    op.drop_column('offers', 'item_indexes')
    op.create_unique_constraint(None, 'offers_history', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offers_history', type_='unique')
    op.add_column('offers', sa.Column('item_indexes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'offers', type_='foreignkey')
    op.create_foreign_key('offers_item_indexes_fkey', 'offers', 'items', ['item_indexes'], ['item_index'])
    op.drop_constraint(None, 'offers', type_='unique')
    op.drop_column('offers', 'offer_item_index')
    op.drop_constraint(None, 'items', type_='unique')
    # ### end Alembic commands ###
