"""empty message

Revision ID: 1f3cc89283e3
Revises: 8b9f1daf3de7
Create Date: 2021-08-21 20:42:24.577360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f3cc89283e3'
down_revision = '8b9f1daf3de7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'offers_active', ['id'])
    op.add_column('offers_history', sa.Column('condition', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'offers_history', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offers_history', type_='unique')
    op.drop_column('offers_history', 'condition')
    op.drop_constraint(None, 'offers_active', type_='unique')
    # ### end Alembic commands ###
