"""empty message

Revision ID: 1f76cf92c119
Revises: 2b8a122c5445
Create Date: 2022-02-03 17:15:04.365017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f76cf92c119'
down_revision = '2b8a122c5445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_items', sa.Column('trade_in_value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction_items', 'trade_in_value')
    # ### end Alembic commands ###
