"""empty message

Revision ID: 212456421ec5
Revises: d03abd2c0829
Create Date: 2021-08-20 12:14:16.904476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '212456421ec5'
down_revision = 'd03abd2c0829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('tcgplayer_id', sa.String(), nullable=True))
    op.alter_column('cards', 'set_search_uri',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'set_search_uri',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.drop_column('cards', 'tcgplayer_id')
    # ### end Alembic commands ###
