"""empty message

Revision ID: 242958a02bdc
Revises: 9684df3a88ff
Create Date: 2021-08-22 15:11:08.562311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '242958a02bdc'
down_revision = '9684df3a88ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'items', ['id'])
    op.drop_constraint('offers_item_index_key', 'offers', type_='unique')
    op.drop_constraint('offers_scryfall_card_id_key', 'offers', type_='unique')
    op.create_unique_constraint(None, 'offers', ['id'])
    op.create_unique_constraint(None, 'offers_history', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offers_history', type_='unique')
    op.drop_constraint(None, 'offers', type_='unique')
    op.create_unique_constraint('offers_scryfall_card_id_key', 'offers', ['scryfall_card_id'])
    op.create_unique_constraint('offers_item_index_key', 'offers', ['item_index'])
    op.drop_constraint(None, 'items', type_='unique')
    # ### end Alembic commands ###
