"""empty message

Revision ID: 2918e91c4896
Revises: 8e4f19d8b07c
Create Date: 2022-01-20 14:24:35.537237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2918e91c4896'
down_revision = '8e4f19d8b07c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ebay_listing',
    sa.Column('database_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('winning_bid', sa.Float(), nullable=True),
    sa.Column('auction_type', sa.String(), nullable=True),
    sa.Column('number_of_bids', sa.Integer(), nullable=True),
    sa.Column('seller_name', sa.String(), nullable=True),
    sa.Column('seller_feedback', sa.Integer(), nullable=True),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.Column('photo_url_1', sa.String(), nullable=True),
    sa.Column('photo_url_2', sa.String(), nullable=True),
    sa.Column('photo_url_3', sa.String(), nullable=True),
    sa.Column('photo_url_4', sa.String(), nullable=True),
    sa.Column('photo_url_5', sa.String(), nullable=True),
    sa.Column('photo_file_name', sa.String(), nullable=True),
    sa.Column('predicted_generic_id', sa.Integer(), nullable=True),
    sa.Column('user_selected_generic_id', sa.Integer(), nullable=True),
    sa.Column('user_approved', sa.Boolean(), nullable=True),
    sa.Column('user_comment', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date_approved', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['predicted_generic_id'], ['generic_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.database_id'], ),
    sa.ForeignKeyConstraint(['user_selected_generic_id'], ['generic_items.id'], ),
    sa.PrimaryKeyConstraint('database_id'),
    sa.UniqueConstraint('database_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ebay_listing')
    # ### end Alembic commands ###
