"""empty message

Revision ID: 2b8a122c5445
Revises: 4f2959dc33eb
Create Date: 2022-02-01 17:02:34.351401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b8a122c5445'
down_revision = '4f2959dc33eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('real_items', sa.Column('qr_label_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('real_items', 'qr_label_url')
    # ### end Alembic commands ###
