"""empty message

Revision ID: 2c4c7614f01d
Revises: 6a7226611e83
Create Date: 2022-02-14 18:32:17.047471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c4c7614f01d'
down_revision = '6a7226611e83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cognito_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cognito_id')
    # ### end Alembic commands ###
