"""empty message

Revision ID: 2dde203e8e41
Revises: e52f3736a873
Create Date: 2021-09-29 00:23:24.371397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dde203e8e41'
down_revision = 'e52f3736a873'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'activities', ['database_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activities', type_='unique')
    # ### end Alembic commands ###
