"""empty message

Revision ID: 2edc93bcb35f
Revises: 559f3d72eb69
Create Date: 2021-09-06 23:54:24.682098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2edc93bcb35f'
down_revision = '559f3d72eb69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('expiration', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('wordpress_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['wordpress_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'wordpress_id')
    op.drop_column('users', 'expiration')
    op.drop_column('users', 'token')
    # ### end Alembic commands ###
