"""empty message

Revision ID: 2ee02c39dd7d
Revises: 5b0b3c79f491
Create Date: 2021-08-21 20:45:31.923105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ee02c39dd7d'
down_revision = '5b0b3c79f491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'offers_active', ['scryfall_card_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offers_active', type_='unique')
    # ### end Alembic commands ###
