"""empty message

Revision ID: 31a1968413e0
Revises: 738a291fd47a
Create Date: 2022-01-24 15:20:26.242331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31a1968413e0'
down_revision = '738a291fd47a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ebay_listing', ['database_id'])
    op.add_column('real_items', sa.Column('item_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('real_items', 'item_hash')
    op.drop_constraint(None, 'ebay_listing', type_='unique')
    # ### end Alembic commands ###
