"""empty message

Revision ID: 3243b30c13b0
Revises: af39be313a27
Create Date: 2021-08-22 14:57:36.402820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3243b30c13b0'
down_revision = 'af39be313a27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('item_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'offers', 'cards', ['item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offers', type_='foreignkey')
    op.drop_column('offers', 'item_id')
    # ### end Alembic commands ###
