"""empty message

Revision ID: 3c34e44dbb5a
Revises: 0662eaf257f0
Create Date: 2021-09-12 11:25:10.354931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c34e44dbb5a'
down_revision = '0662eaf257f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('website', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchants', 'website')
    # ### end Alembic commands ###
