"""empty message

Revision ID: 3ddf5acfe187
Revises: 
Create Date: 2021-08-19 22:37:57.766438

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3ddf5acfe187'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('scryfall_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('racist_card', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('set', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tcgplayer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cardmarket_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mana_cost', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type_line', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('artist', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('power', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('toughness', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('colors', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('keywords', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rarity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image_uris', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('foil', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('nonfoil', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('reserved_list', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('oracle_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('flavor_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('collector_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('identifier', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('item_index', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('etched_foil', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='csv_public_cards_aug_19_2021_pkey')
    )
    # ### end Alembic commands ###
