"""empty message

Revision ID: 3e9645653a0b
Revises: d7c1b1feeb8d
Create Date: 2021-09-25 09:23:53.902775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e9645653a0b'
down_revision = 'd7c1b1feeb8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'real_item_defects', ['database_id'])
    op.add_column('real_items', sa.Column('forsale_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('real_items', 'forsale_price')
    op.drop_constraint(None, 'real_item_defects', type_='unique')
    # ### end Alembic commands ###
