"""empty message

Revision ID: 3ef2ef211a1b
Revises: 4ac1f55aa725
Create Date: 2021-09-25 14:34:11.632861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ef2ef211a1b'
down_revision = '4ac1f55aa725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('real_items', sa.Column('status', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'real_items_defects', ['database_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'real_items_defects', type_='unique')
    op.drop_column('real_items', 'status')
    # ### end Alembic commands ###
