"""empty message

Revision ID: 44d841bdeaa5
Revises: d9d281111154
Create Date: 2021-09-11 11:17:37.441814

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '44d841bdeaa5'
down_revision = 'd9d281111154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants_condition_multiplier',
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('condition_id', sa.Integer(), nullable=True),
    sa.Column('multiplier', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['condition_id'], ['conditions.database_id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.database_id'], ),
    sa.PrimaryKeyConstraint('database_id'),
    sa.UniqueConstraint('database_id')
    )
    op.create_unique_constraint(None, 'activity', ['database_id'])
    op.add_column('conditions', sa.Column('us_name', sa.String(), nullable=True))
    op.add_column('conditions', sa.Column('eu_name', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'conditions', ['short_code'])
    op.drop_column('conditions', 'display_name')
    op.drop_column('conditions', 'trade_in_multiplier')
    op.drop_column('conditions', 'selling_multiplier')
    op.add_column('merchants', sa.Column('location', sa.String(), nullable=True))
    op.add_column('merchants', sa.Column('last_updated', sa.Date(), nullable=True))
    op.create_unique_constraint(None, 'topics', ['database_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topics', type_='unique')
    op.drop_column('merchants', 'last_updated')
    op.drop_column('merchants', 'location')
    op.add_column('conditions', sa.Column('selling_multiplier', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('conditions', sa.Column('trade_in_multiplier', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('conditions', sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'conditions', type_='unique')
    op.drop_column('conditions', 'eu_name')
    op.drop_column('conditions', 'us_name')
    op.drop_constraint(None, 'activity', type_='unique')
    op.drop_table('merchants_condition_multiplier')
    # ### end Alembic commands ###
