"""empty message

Revision ID: 4aae462fbdd3
Revises: 0c0855f9d8a6
Create Date: 2021-12-14 12:16:24.059991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aae462fbdd3'
down_revision = '0c0855f9d8a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('real_items', sa.Column('user_list', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('real_items', 'user_list')
    # ### end Alembic commands ###
