"""empty message

Revision ID: 4ac1f55aa725
Revises: de5bf9e400b6
Create Date: 2021-09-25 14:25:47.416495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ac1f55aa725'
down_revision = 'de5bf9e400b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('real_items_defects',
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('defect_name', sa.String(), nullable=True),
    sa.Column('realitem_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['realitem_id'], ['real_items.database_id'], ),
    sa.PrimaryKeyConstraint('database_id'),
    sa.UniqueConstraint('database_id')
    )
    op.drop_table('real_item_defects')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('real_item_defects',
    sa.Column('database_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('defect_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('realitem_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['realitem_id'], ['real_items.database_id'], name='real_item_defects_realitem_id_fkey'),
    sa.PrimaryKeyConstraint('database_id', name='real_item_defects_pkey'),
    sa.UniqueConstraint('database_id', name='real_item_defects_database_id_key')
    )
    op.drop_table('real_items_defects')
    # ### end Alembic commands ###
