"""empty message

Revision ID: 4f2959dc33eb
Revises: 73694061046c
Create Date: 2022-02-01 16:55:52.848110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f2959dc33eb'
down_revision = '73694061046c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('real_items', sa.Column('qr_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('real_items', 'qr_url')
    # ### end Alembic commands ###
