"""empty message

Revision ID: 59b2f7f3e3b2
Revises: d5ee0e8ee43d
Create Date: 2021-08-22 11:20:07.589725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59b2f7f3e3b2'
down_revision = 'd5ee0e8ee43d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scryfall_card_id', sa.String(), nullable=True),
    sa.Column('item_index', sa.String(), nullable=True),
    sa.Column('last_updated', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('item_index'),
    sa.UniqueConstraint('scryfall_card_id')
    )
    op.drop_table('offers_active')
    op.create_unique_constraint(None, 'cards', ['id'])
    op.create_unique_constraint(None, 'offers_history', ['id'])
    op.drop_constraint('offers_history_offers_active_id_fkey', 'offers_history', type_='foreignkey')
    op.drop_column('offers_history', 'offers_active_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers_history', sa.Column('offers_active_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('offers_history_offers_active_id_fkey', 'offers_history', 'offers_active', ['offers_active_id'], ['id'])
    op.drop_constraint(None, 'offers_history', type_='unique')
    op.drop_constraint(None, 'cards', type_='unique')
    op.create_table('offers_active',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('scryfall_card_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('item_index', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_updated', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='offers_active_pkey'),
    sa.UniqueConstraint('item_index', name='offers_active_item_index_key'),
    sa.UniqueConstraint('scryfall_card_id', name='offers_active_scryfall_card_id_key')
    )
    op.drop_table('offers')
    # ### end Alembic commands ###
