"""empty message

Revision ID: 5b0b3c79f491
Revises: 1f3cc89283e3
Create Date: 2021-08-21 20:44:05.633853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b0b3c79f491'
down_revision = '1f3cc89283e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('offers_history_offers_active_id_fkey', 'offers_history', type_='foreignkey')
    op.create_foreign_key(None, 'offers_history', 'offers_active', ['offers_active_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offers_history', type_='foreignkey')
    op.create_foreign_key('offers_history_offers_active_id_fkey', 'offers_history', 'sets', ['offers_active_id'], ['id'])
    # ### end Alembic commands ###
