"""empty message

Revision ID: 5b5ba74fc6f8
Revises: c7a58424bfc4
Create Date: 2021-08-21 12:39:34.373459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5b5ba74fc6f8'
down_revision = 'c7a58424bfc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offer_history')
    op.drop_table('current_offers')
    op.add_column('cards', sa.Column('oracle_id', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('multiverse_ids', sa.Integer(), nullable=True))
    op.add_column('cards', sa.Column('mtgo_id', sa.Integer(), nullable=True))
    op.add_column('cards', sa.Column('produced_mana', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('mtgo_foil_id', sa.Integer(), nullable=True))
    op.add_column('cards', sa.Column('legalities', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('full_art', sa.Boolean(), nullable=True))
    op.add_column('cards', sa.Column('textless', sa.Boolean(), nullable=True))
    op.add_column('cards', sa.Column('loyalty', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('oversized', sa.Boolean(), nullable=True))
    op.add_column('cards', sa.Column('card_back_id', sa.Integer(), nullable=True))
    op.add_column('cards', sa.Column('games', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('rarity', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('variation', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('variation_of', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('layout', sa.String(), nullable=True))
    op.drop_column('cards', 'date_inserted')
    op.drop_column('cards', 'date_updated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('date_updated', sa.DATE(), server_default=sa.text("'2021-08-21'::date"), autoincrement=False, nullable=True))
    op.add_column('cards', sa.Column('date_inserted', sa.DATE(), server_default=sa.text("'2021-08-21'::date"), autoincrement=False, nullable=True))
    op.drop_column('cards', 'layout')
    op.drop_column('cards', 'variation_of')
    op.drop_column('cards', 'variation')
    op.drop_column('cards', 'rarity')
    op.drop_column('cards', 'games')
    op.drop_column('cards', 'card_back_id')
    op.drop_column('cards', 'oversized')
    op.drop_column('cards', 'loyalty')
    op.drop_column('cards', 'textless')
    op.drop_column('cards', 'full_art')
    op.drop_column('cards', 'legalities')
    op.drop_column('cards', 'mtgo_foil_id')
    op.drop_column('cards', 'produced_mana')
    op.drop_column('cards', 'mtgo_id')
    op.drop_column('cards', 'multiverse_ids')
    op.drop_column('cards', 'oracle_id')
    op.create_table('current_offers',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('current_offers_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('offer_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('offer_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_updated', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='current_offers_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('offer_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('merchant', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('offer_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('item_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('current_offers_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['current_offers_id'], ['current_offers.id'], name='offer_history_current_offers_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='offer_history_pkey')
    )
    # ### end Alembic commands ###
