"""empty message

Revision ID: 5b96d5b378b0
Revises: 1ce9a7982fc9
Create Date: 2021-08-23 13:50:14.140715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b96d5b378b0'
down_revision = '1ce9a7982fc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('offers_offer_item_index_fkey', 'offers', type_='foreignkey')
    op.drop_column('offers', 'offer_item_index')
    op.drop_constraint('offers_history_offers_id_fkey', 'offers_history', type_='foreignkey')
    op.drop_column('offers_history', 'offers_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers_history', sa.Column('offers_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('offers_history_offers_id_fkey', 'offers_history', 'offers', ['offers_id'], ['id'])
    op.add_column('offers', sa.Column('offer_item_index', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('offers_offer_item_index_fkey', 'offers', 'items', ['offer_item_index'], ['item_index'])
    # ### end Alembic commands ###
