"""empty message

Revision ID: 5bd802099d77
Revises: 7e0ad70a6bcd
Create Date: 2021-12-29 19:47:02.904359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bd802099d77'
down_revision = '7e0ad70a6bcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers_time_series',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.Column('date_updated', sa.Date(), nullable=True),
    sa.Column('history', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offers_time_series')
    # ### end Alembic commands ###
