"""empty message

Revision ID: 5e07c88263dd
Revises: 1675413e767f
Create Date: 2021-09-25 00:01:37.835016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e07c88263dd'
down_revision = '1675413e767f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('real_items', sa.Column('defect_dented', sa.Boolean(), nullable=True))
    op.add_column('real_items', sa.Column('defect_scratched', sa.Boolean(), nullable=True))
    op.add_column('real_items', sa.Column('defect_roller_lines', sa.Boolean(), nullable=True))
    op.add_column('real_items', sa.Column('defect_clouding', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('real_items', 'defect_clouding')
    op.drop_column('real_items', 'defect_roller_lines')
    op.drop_column('real_items', 'defect_scratched')
    op.drop_column('real_items', 'defect_dented')
    # ### end Alembic commands ###
