"""empty message

Revision ID: 5e7a496eef74
Revises: 0ed1b9e19bb5
Create Date: 2022-01-13 16:00:31.797033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e7a496eef74'
down_revision = '0ed1b9e19bb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('view_mode', sa.String(), nullable=True))
    op.add_column('users', sa.Column('color_theme', sa.String(), nullable=True))
    op.add_column('users', sa.Column('per_page', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'per_page')
    op.drop_column('users', 'color_theme')
    op.drop_column('users', 'view_mode')
    # ### end Alembic commands ###
