"""empty message

Revision ID: 5faf63e4c192
Revises: 90deb6ec7012
Create Date: 2021-10-26 15:50:10.947000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5faf63e4c192'
down_revision = '90deb6ec7012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_status',
    sa.Column('state', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('state')
    )
    op.create_table('trade_items',
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('real_item_id', sa.Integer(), nullable=True),
    sa.Column('side', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['real_item_id'], ['real_items.database_id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.database_id'], ),
    sa.PrimaryKeyConstraint('database_id')
    )
    op.add_column('real_items', sa.Column('trade_status', sa.String(), nullable=True))
    op.drop_constraint('trades_right_collection_id_fkey', 'trades', type_='foreignkey')
    op.drop_constraint('trades_left_collection_id_fkey', 'trades', type_='foreignkey')
    op.create_foreign_key(None, 'trades', 'trade_status', ['status'], ['state'])
    op.drop_column('trades', 'right_collection_id')
    op.drop_column('trades', 'left_collection_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('left_collection_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('trades', sa.Column('right_collection_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.create_foreign_key('trades_left_collection_id_fkey', 'trades', 'item_collections', ['left_collection_id'], ['database_id'])
    op.create_foreign_key('trades_right_collection_id_fkey', 'trades', 'item_collections', ['right_collection_id'], ['database_id'])
    op.drop_column('real_items', 'trade_status')
    op.drop_table('trade_items')
    op.drop_table('trade_status')
    # ### end Alembic commands ###
