"""empty message

Revision ID: 6726226e44a0
Revises: 3ef2ef211a1b
Create Date: 2021-09-28 23:06:27.631118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6726226e44a0'
down_revision = '3ef2ef211a1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('object', sa.String(), nullable=False),
    sa.Column('objectEntity', sa.String(), nullable=True),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('targetEntity', sa.String(), nullable=True),
    sa.Column('verb', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('timestamp', sa.Date(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('offersId', sa.Integer(), nullable=True),
    sa.Column('realItemId', sa.Integer(), nullable=True),
    sa.Column('collectionId', sa.Integer(), nullable=True),
    sa.Column('genericItemId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collectionId'], ['item_collections.database_id'], ),
    sa.ForeignKeyConstraint(['genericItemId'], ['generic_items.id'], ),
    sa.ForeignKeyConstraint(['offersId'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['realItemId'], ['real_items.database_id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.database_id'], ),
    sa.PrimaryKeyConstraint('database_id'),
    sa.UniqueConstraint('database_id')
    )
    op.create_table('subscriptions',
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('subscriberId', sa.Integer(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('offersId', sa.Integer(), nullable=True),
    sa.Column('realItemId', sa.Integer(), nullable=True),
    sa.Column('collectionId', sa.Integer(), nullable=True),
    sa.Column('genericItemId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collectionId'], ['item_collections.database_id'], ),
    sa.ForeignKeyConstraint(['genericItemId'], ['generic_items.id'], ),
    sa.ForeignKeyConstraint(['offersId'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['realItemId'], ['real_items.database_id'], ),
    sa.ForeignKeyConstraint(['subscriberId'], ['users.database_id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.database_id'], ),
    sa.PrimaryKeyConstraint('database_id')
    )
    op.drop_table('activity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('actor', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('generator', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('database_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('icon', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('object', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('published', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('target', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('verb', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('database_id', name='activity_pkey'),
    sa.UniqueConstraint('database_id', name='activity_database_id_key')
    )
    op.drop_table('subscriptions')
    op.drop_table('activities')
    # ### end Alembic commands ###
