"""empty message

Revision ID: 69f2a2b74075
Revises: 79d17b437bc6
Create Date: 2022-02-03 21:48:20.411357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69f2a2b74075'
down_revision = '79d17b437bc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('real_items', sa.Column('recent_transaction', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('real_items', 'recent_transaction')
    # ### end Alembic commands ###
