"""empty message

Revision ID: 6bd21f4d1ff9
Revises: 575eaa8b8994
Create Date: 2021-09-30 12:34:31.357391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bd21f4d1ff9'
down_revision = '575eaa8b8994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('real_item_id', sa.Integer(), nullable=False))
    op.drop_constraint('media_realitem_id_fkey', 'media', type_='foreignkey')
    op.create_foreign_key(None, 'media', 'real_items', ['real_item_id'], ['database_id'])
    op.drop_column('media', 'realitem_id')
    op.add_column('real_items_defects', sa.Column('real_item_id', sa.Integer(), nullable=False))
    op.drop_constraint('real_items_defects_realitem_id_fkey', 'real_items_defects', type_='foreignkey')
    op.create_foreign_key(None, 'real_items_defects', 'real_items', ['real_item_id'], ['database_id'])
    op.drop_column('real_items_defects', 'realitem_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('real_items_defects', sa.Column('realitem_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'real_items_defects', type_='foreignkey')
    op.create_foreign_key('real_items_defects_realitem_id_fkey', 'real_items_defects', 'real_items', ['realitem_id'], ['database_id'])
    op.drop_column('real_items_defects', 'real_item_id')
    op.add_column('media', sa.Column('realitem_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.create_foreign_key('media_realitem_id_fkey', 'media', 'real_items', ['realitem_id'], ['database_id'])
    op.drop_column('media', 'real_item_id')
    # ### end Alembic commands ###
