"""empty message

Revision ID: 6c29b87dcd4a
Revises: 9fa683b40019
Create Date: 2021-09-11 16:20:32.931586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c29b87dcd4a'
down_revision = '9fa683b40019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers_history', 'condition_string')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers_history', sa.Column('condition_string', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
