"""empty message

Revision ID: 6cbef060159f
Revises: fffd372929a6
Create Date: 2021-08-20 11:02:58.341516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cbef060159f'
down_revision = 'fffd372929a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'sets', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sets', type_='unique')
    # ### end Alembic commands ###
