"""empty message

Revision ID: 6f04d9835884
Revises: f33dadfb4517
Create Date: 2021-08-20 16:07:27.704280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f04d9835884'
down_revision = 'f33dadfb4517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'item_index',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'item_index',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
