"""empty message

Revision ID: 73694061046c
Revises: cca66701671f
Create Date: 2022-02-01 06:40:16.958393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73694061046c'
down_revision = 'cca66701671f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ebay_listing', sa.Column('predicted_generic_id_list', sa.String(), nullable=True))
    op.add_column('listing_feedback', sa.Column('is_correct', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing_feedback', 'is_correct')
    op.drop_column('ebay_listing', 'predicted_generic_id_list')
    # ### end Alembic commands ###
