"""empty message

Revision ID: 78f9ab674b29
Revises: a57c5bb96fa4
Create Date: 2021-08-20 10:30:15.398893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78f9ab674b29'
down_revision = 'a57c5bb96fa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scryfall_set_id', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('mtgo_code', sa.String(), nullable=True),
    sa.Column('arena_code', sa.String(), nullable=True),
    sa.Column('tcgplayer_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('uri', sa.String(), nullable=True),
    sa.Column('scryfall_uri', sa.String(), nullable=True),
    sa.Column('search_uri', sa.String(), nullable=True),
    sa.Column('released_at', sa.Date(), nullable=True),
    sa.Column('set_type', sa.String(), nullable=True),
    sa.Column('digital', sa.Boolean(), nullable=True),
    sa.Column('nonfoil_only', sa.Boolean(), nullable=True),
    sa.Column('foil_only', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sets')
    # ### end Alembic commands ###
