"""empty message

Revision ID: 794dd5d746ad
Revises: 2c4c7614f01d
Create Date: 2022-02-20 20:38:38.290063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '794dd5d746ad'
down_revision = '2c4c7614f01d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_items', sa.Column('trade_in_value_NM', sa.Float(), nullable=True))
    op.add_column('transaction_items', sa.Column('web_approval', sa.Boolean(), nullable=True))
    op.add_column('transaction_items', sa.Column('final_approval', sa.Boolean(), nullable=True))
    op.add_column('transaction_items', sa.Column('admin_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction_items', 'admin_price')
    op.drop_column('transaction_items', 'final_approval')
    op.drop_column('transaction_items', 'web_approval')
    op.drop_column('transaction_items', 'trade_in_value_NM')
    # ### end Alembic commands ###
