"""empty message

Revision ID: 7d9bdb5e8ce0
Revises: bacb76dabfeb
Create Date: 2021-09-11 12:57:35.741690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d9bdb5e8ce0'
down_revision = 'bacb76dabfeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers_history', sa.Column('condition_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'offers_history', 'conditions', ['condition_id'], ['database_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offers_history', type_='foreignkey')
    op.drop_column('offers_history', 'condition_id')
    # ### end Alembic commands ###
