"""empty message

Revision ID: 7e0ad70a6bcd
Revises: f1619639e22f
Create Date: 2021-12-15 14:21:25.310901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e0ad70a6bcd'
down_revision = 'f1619639e22f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('real_items', sa.Column('transaction_status', sa.String(), nullable=True))
    op.drop_column('real_items', 'trade_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('real_items', sa.Column('trade_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('real_items', 'transaction_status')
    # ### end Alembic commands ###
