"""empty message

Revision ID: 82ee092e00f5
Revises: 88bbf91cd2eb
Create Date: 2021-08-23 13:34:41.280062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82ee092e00f5'
down_revision = '88bbf91cd2eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'offers', ['item_index'])
    op.create_foreign_key(None, 'offers', 'items', ['scryfall_card_id'], ['scryfall_card_id'])
    op.create_foreign_key(None, 'offers', 'items', ['item_index'], ['item_index'])
    op.add_column('offers_history', sa.Column('offers_id', sa.Integer(), nullable=False))
    op.drop_constraint('offers_history_offer_fkey', 'offers_history', type_='foreignkey')
    op.create_foreign_key(None, 'offers_history', 'offers', ['offers_id'], ['id'])
    op.drop_column('offers_history', 'offer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers_history', sa.Column('offer', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'offers_history', type_='foreignkey')
    op.create_foreign_key('offers_history_offer_fkey', 'offers_history', 'offers', ['offer'], ['id'])
    op.drop_column('offers_history', 'offers_id')
    op.drop_constraint(None, 'offers', type_='foreignkey')
    op.drop_constraint(None, 'offers', type_='foreignkey')
    op.drop_constraint(None, 'offers', type_='unique')
    # ### end Alembic commands ###
