"""empty message

Revision ID: 8458dc4eaabd
Revises: 6726226e44a0
Create Date: 2021-09-29 00:17:01.004795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8458dc4eaabd'
down_revision = '6726226e44a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'activities', ['database_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activities', type_='unique')
    # ### end Alembic commands ###
