"""empty message

Revision ID: 8b8a2b491aec
Revises: 894e4c50f1fc
Create Date: 2021-09-11 12:41:52.662804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b8a2b491aec'
down_revision = '894e4c50f1fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers_history', sa.Column('condition', sa.Integer(), nullable=True))
    op.drop_constraint('offers_history_condition_id_fkey', 'offers_history', type_='foreignkey')
    op.create_foreign_key(None, 'offers_history', 'conditions', ['condition'], ['database_id'])
    op.drop_column('offers_history', 'condition_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers_history', sa.Column('condition_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'offers_history', type_='foreignkey')
    op.create_foreign_key('offers_history_condition_id_fkey', 'offers_history', 'conditions', ['condition_id'], ['database_id'])
    op.drop_column('offers_history', 'condition')
    # ### end Alembic commands ###
