"""empty message

Revision ID: 8b9f1daf3de7
Revises: 5b5ba74fc6f8
Create Date: 2021-08-21 20:15:32.022303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b9f1daf3de7'
down_revision = '5b5ba74fc6f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers_active',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scryfall_card_id', sa.String(), nullable=True),
    sa.Column('item_index', sa.String(), nullable=True),
    sa.Column('last_updated', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('item_index')
    )
    op.create_table('offers_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scryfall_card_id', sa.String(), nullable=True),
    sa.Column('item_index', sa.String(), nullable=True),
    sa.Column('last_updated', sa.Date(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('merchant', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('card_type', sa.String(), nullable=True),
    sa.Column('offers_active_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['offers_active_id'], ['sets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('item_index')
    )
    op.create_unique_constraint(None, 'cards', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cards', type_='unique')
    op.drop_table('offers_history')
    op.drop_table('offers_active')
    # ### end Alembic commands ###
