"""empty message

Revision ID: 8e4f19d8b07c
Revises: 5e7a496eef74
Create Date: 2022-01-17 10:39:18.179604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e4f19d8b07c'
down_revision = '5e7a496eef74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('date_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_updated')
    op.drop_column('users', 'date_created')
    # ### end Alembic commands ###
