"""empty message

Revision ID: 90deb6ec7012
Revises: e0fd8fc6afbb
Create Date: 2021-10-26 10:26:02.045572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90deb6ec7012'
down_revision = 'e0fd8fc6afbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trades',
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.Column('date_updated', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('left_collection_id', sa.Integer(), nullable=True),
    sa.Column('left_credit', sa.Float(), nullable=True),
    sa.Column('left_owner', sa.Integer(), nullable=True),
    sa.Column('right_collection_id', sa.Integer(), nullable=True),
    sa.Column('right_credit', sa.Float(), nullable=True),
    sa.Column('right_owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['left_collection_id'], ['item_collections.database_id'], ),
    sa.ForeignKeyConstraint(['left_owner'], ['users.database_id'], ),
    sa.ForeignKeyConstraint(['right_collection_id'], ['item_collections.database_id'], ),
    sa.ForeignKeyConstraint(['right_owner'], ['users.database_id'], ),
    sa.PrimaryKeyConstraint('database_id')
    )
    op.create_unique_constraint(None, 'latest_offers', ['database_id'])
    op.create_unique_constraint(None, 'latest_offers_history', ['database_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'latest_offers_history', type_='unique')
    op.drop_constraint(None, 'latest_offers', type_='unique')
    op.drop_table('trades')
    # ### end Alembic commands ###
