"""empty message

Revision ID: 925cb5c84e29
Revises: 5bd802099d77
Create Date: 2021-12-29 19:59:23.816894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '925cb5c84e29'
down_revision = '5bd802099d77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offers_time_series', 'date_created',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('offers_time_series', 'date_updated',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offers_time_series', 'date_updated',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('offers_time_series', 'date_created',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
