"""empty message

Revision ID: 957e2a42b07b
Revises: 194272f626d6
Create Date: 2021-08-23 13:53:39.189376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '957e2a42b07b'
down_revision = '194272f626d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('item_index', sa.String(), nullable=True))
    op.create_foreign_key(None, 'offers', 'items', ['scryfall_card_id'], ['scryfall_card_id'])
    op.create_foreign_key(None, 'offers', 'items', ['item_index'], ['item_index'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offers', type_='foreignkey')
    op.drop_constraint(None, 'offers', type_='foreignkey')
    op.drop_column('offers', 'item_index')
    # ### end Alembic commands ###
