"""empty message

Revision ID: a0d0eb93254e
Revises: bfc4112b9a2a
Create Date: 2021-12-08 17:14:36.165429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0d0eb93254e'
down_revision = 'bfc4112b9a2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conditions',
    sa.Column('us_code', sa.String(), nullable=False),
    sa.Column('eu_code', sa.String(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('us_code'),
    sa.UniqueConstraint('us_code')
    )
    op.create_table('merchants',
    sa.Column('shortcode', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('shortcode'),
    sa.UniqueConstraint('shortcode')
    )
    op.create_table('sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scryfall_set_id', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('mtgo_code', sa.String(), nullable=True),
    sa.Column('arena_code', sa.String(), nullable=True),
    sa.Column('tcgplayer_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('uri', sa.String(), nullable=True),
    sa.Column('scryfall_uri', sa.String(), nullable=True),
    sa.Column('search_uri', sa.String(), nullable=True),
    sa.Column('released_at', sa.Date(), nullable=True),
    sa.Column('set_type', sa.String(), nullable=True),
    sa.Column('digital', sa.Boolean(), nullable=True),
    sa.Column('nonfoil_only', sa.Boolean(), nullable=True),
    sa.Column('foil_only', sa.Boolean(), nullable=True),
    sa.Column('icon_svg_uri', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('scryfall_set_id')
    )
    op.create_table('topics',
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('database_id'),
    sa.UniqueConstraint('database_id')
    )
    op.create_table('trade_status',
    sa.Column('state', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('state')
    )
    op.create_table('transaction_status',
    sa.Column('state', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('state')
    )
    op.create_table('users',
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('security_role', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('expiration', sa.Integer(), nullable=True),
    sa.Column('wordpress_id', sa.Integer(), nullable=True),
    sa.Column('credit', sa.Float(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address_line_one', sa.String(), nullable=True),
    sa.Column('address_line_two', sa.String(), nullable=True),
    sa.Column('address_state', sa.String(), nullable=True),
    sa.Column('address_city', sa.String(), nullable=True),
    sa.Column('address_country', sa.String(), nullable=True),
    sa.Column('address_zipcode', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('real_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('database_id'),
    sa.UniqueConstraint('database_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('wordpress_id')
    )
    op.create_table('generic_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oracle_id', sa.String(), nullable=True),
    sa.Column('multiverse_ids', sa.String(), nullable=True),
    sa.Column('mtgo_id', sa.String(), nullable=True),
    sa.Column('produced_mana', sa.String(), nullable=True),
    sa.Column('mtgo_foil_id', sa.String(), nullable=True),
    sa.Column('scryfall_card_id', sa.String(), nullable=True),
    sa.Column('legalities', sa.String(), nullable=True),
    sa.Column('full_art', sa.Boolean(), nullable=True),
    sa.Column('textless', sa.Boolean(), nullable=True),
    sa.Column('loyalty', sa.String(), nullable=True),
    sa.Column('oversized', sa.Boolean(), nullable=True),
    sa.Column('frame', sa.String(), nullable=True),
    sa.Column('card_back_id', sa.String(), nullable=True),
    sa.Column('games', sa.String(), nullable=True),
    sa.Column('lang', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('uri', sa.String(), nullable=True),
    sa.Column('rarity', sa.String(), nullable=True),
    sa.Column('variation', sa.String(), nullable=True),
    sa.Column('variation_of', sa.String(), nullable=True),
    sa.Column('layout', sa.String(), nullable=True),
    sa.Column('scryfall_uri', sa.String(), nullable=True),
    sa.Column('cmc', sa.Float(), nullable=True),
    sa.Column('cardmarket_id', sa.String(), nullable=True),
    sa.Column('tcgplayer_id', sa.String(), nullable=True),
    sa.Column('color_identity', sa.String(), nullable=True),
    sa.Column('colors', sa.String(), nullable=True),
    sa.Column('keywords', sa.String(), nullable=True),
    sa.Column('image_uris', sa.String(), nullable=True),
    sa.Column('foil', sa.Boolean(), nullable=True),
    sa.Column('nonfoil', sa.Boolean(), nullable=True),
    sa.Column('etchedfoil', sa.Boolean(), nullable=True),
    sa.Column('mana_cost', sa.String(), nullable=True),
    sa.Column('oracle_text', sa.String(), nullable=True),
    sa.Column('power', sa.String(), nullable=True),
    sa.Column('reserved', sa.Boolean(), nullable=True),
    sa.Column('toughness', sa.String(), nullable=True),
    sa.Column('type_line', sa.String(), nullable=True),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('booster', sa.String(), nullable=True),
    sa.Column('border_color', sa.String(), nullable=True),
    sa.Column('collector_number', sa.String(), nullable=True),
    sa.Column('flavor_name', sa.String(), nullable=True),
    sa.Column('flavor_text', sa.String(), nullable=True),
    sa.Column('illustration_id', sa.String(), nullable=True),
    sa.Column('printed_name', sa.String(), nullable=True),
    sa.Column('printed_text', sa.String(), nullable=True),
    sa.Column('printed_type_line', sa.String(), nullable=True),
    sa.Column('promo', sa.Boolean(), nullable=True),
    sa.Column('purchase_uris', sa.String(), nullable=True),
    sa.Column('released_at', sa.Date(), nullable=True),
    sa.Column('scryfall_set_uri', sa.String(), nullable=True),
    sa.Column('set_name', sa.String(), nullable=True),
    sa.Column('set_search_uri', sa.String(), nullable=True),
    sa.Column('set_type', sa.String(), nullable=True),
    sa.Column('set_uri', sa.String(), nullable=True),
    sa.Column('set', sa.String(), nullable=True),
    sa.Column('image_uri_small', sa.String(), nullable=True),
    sa.Column('image_uri_normal', sa.String(), nullable=True),
    sa.Column('image_uri_large', sa.String(), nullable=True),
    sa.Column('image_uri_png', sa.String(), nullable=True),
    sa.Column('item_index', sa.String(), nullable=True),
    sa.Column('scryfall_set_id', sa.String(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scryfall_set_id'], ['sets.scryfall_set_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('item_index')
    )
    op.create_table('item_collections',
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('trashed', sa.Boolean(), nullable=True),
    sa.Column('order_status', sa.String(), nullable=True),
    sa.Column('admin_approved', sa.Boolean(), nullable=True),
    sa.Column('admin_comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.database_id'], ),
    sa.PrimaryKeyConstraint('database_id'),
    sa.UniqueConstraint('database_id')
    )
    op.create_table('merchants_condition_multiplier',
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('merchant', sa.String(), nullable=True),
    sa.Column('condition_id', sa.String(), nullable=True),
    sa.Column('multiplier', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['condition_id'], ['conditions.us_code'], ),
    sa.ForeignKeyConstraint(['merchant'], ['merchants.shortcode'], ),
    sa.PrimaryKeyConstraint('database_id'),
    sa.UniqueConstraint('database_id')
    )
    op.create_table('notifications',
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.Column('date_updated', sa.Date(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.database_id'], ),
    sa.PrimaryKeyConstraint('database_id')
    )
    op.create_table('trades',
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.Column('date_updated', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('left_credit', sa.Float(), nullable=True),
    sa.Column('left_owner', sa.Integer(), nullable=True),
    sa.Column('left_confirm', sa.Boolean(), nullable=True),
    sa.Column('right_credit', sa.Float(), nullable=True),
    sa.Column('right_owner', sa.Integer(), nullable=True),
    sa.Column('right_confirm', sa.Boolean(), nullable=True),
    sa.Column('left_close', sa.Boolean(), nullable=True),
    sa.Column('right_close', sa.Boolean(), nullable=True),
    sa.Column('half_closed_side', sa.String(), nullable=True),
    sa.Column('paypal_costs', sa.Float(), nullable=True),
    sa.Column('shipping_and_handling_costs', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['left_owner'], ['users.database_id'], ),
    sa.ForeignKeyConstraint(['right_owner'], ['users.database_id'], ),
    sa.ForeignKeyConstraint(['status'], ['trade_status.state'], ),
    sa.PrimaryKeyConstraint('database_id')
    )
    op.create_table('transactions',
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.Column('date_updated', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('left_credit', sa.Float(), nullable=True),
    sa.Column('left_owner', sa.Integer(), nullable=True),
    sa.Column('left_confirm', sa.Boolean(), nullable=True),
    sa.Column('right_credit', sa.Float(), nullable=True),
    sa.Column('right_owner', sa.Integer(), nullable=True),
    sa.Column('right_confirm', sa.Boolean(), nullable=True),
    sa.Column('left_close', sa.Boolean(), nullable=True),
    sa.Column('right_close', sa.Boolean(), nullable=True),
    sa.Column('half_closed_side', sa.String(), nullable=True),
    sa.Column('paypal_costs', sa.Float(), nullable=True),
    sa.Column('shipping_and_handling_costs', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['left_owner'], ['users.database_id'], ),
    sa.ForeignKeyConstraint(['right_owner'], ['users.database_id'], ),
    sa.ForeignKeyConstraint(['status'], ['transaction_status.state'], ),
    sa.PrimaryKeyConstraint('database_id')
    )
    op.create_table('user_lists',
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.Column('date_updated', sa.Date(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['users.database_id'], ),
    sa.PrimaryKeyConstraint('database_id')
    )
    op.create_table('collection_history',
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('collectionId', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Date(), nullable=True),
    sa.Column('retail_value', sa.Float(), nullable=True),
    sa.Column('pm_value', sa.Float(), nullable=True),
    sa.Column('number_of_items', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collectionId'], ['item_collections.database_id'], ),
    sa.PrimaryKeyConstraint('database_id')
    )
    op.create_table('latest_offers',
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('scryfall_card_id', sa.String(), nullable=True),
    sa.Column('item_index', sa.String(), nullable=True),
    sa.Column('last_updated', sa.Date(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['condition'], ['conditions.us_code'], ),
    sa.ForeignKeyConstraint(['item_id'], ['generic_items.id'], ),
    sa.PrimaryKeyConstraint('database_id'),
    sa.UniqueConstraint('database_id')
    )
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scryfall_card_id', sa.String(), nullable=True),
    sa.Column('item_index', sa.String(), nullable=True),
    sa.Column('last_updated', sa.Date(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['condition'], ['conditions.us_code'], ),
    sa.ForeignKeyConstraint(['item_id'], ['generic_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('real_items',
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('item_collections_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('creator', sa.Integer(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.Column('date_updated', sa.Date(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('cost_basis', sa.Float(), nullable=True),
    sa.Column('fmv', sa.Float(), nullable=True),
    sa.Column('trade_in_value', sa.Float(), nullable=True),
    sa.Column('woocommerce_url', sa.String(), nullable=True),
    sa.Column('woocommerce_product_id', sa.Integer(), nullable=True),
    sa.Column('forsale_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('trade_status', sa.String(), nullable=True),
    sa.Column('user_list', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['condition'], ['conditions.us_code'], ),
    sa.ForeignKeyConstraint(['creator'], ['users.database_id'], ),
    sa.ForeignKeyConstraint(['item_collections_id'], ['item_collections.database_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['generic_items.id'], ),
    sa.ForeignKeyConstraint(['owner'], ['users.database_id'], ),
    sa.PrimaryKeyConstraint('database_id'),
    sa.UniqueConstraint('database_id')
    )
    op.create_table('activities',
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('object', sa.String(), nullable=False),
    sa.Column('objectEntity', sa.String(), nullable=True),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('targetEntity', sa.String(), nullable=True),
    sa.Column('verb', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('timestamp', sa.Date(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('offersId', sa.Integer(), nullable=True),
    sa.Column('realItemId', sa.Integer(), nullable=True),
    sa.Column('collectionId', sa.Integer(), nullable=True),
    sa.Column('genericItemId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collectionId'], ['item_collections.database_id'], ),
    sa.ForeignKeyConstraint(['genericItemId'], ['generic_items.id'], ),
    sa.ForeignKeyConstraint(['offersId'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['realItemId'], ['real_items.database_id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.database_id'], ),
    sa.PrimaryKeyConstraint('database_id'),
    sa.UniqueConstraint('database_id')
    )
    op.create_table('latest_offers_history',
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('scryfall_card_id', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('merchant', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('card_type', sa.String(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('offers_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['condition'], ['conditions.us_code'], ),
    sa.ForeignKeyConstraint(['merchant'], ['merchants.shortcode'], ),
    sa.ForeignKeyConstraint(['offers_id'], ['latest_offers.database_id'], ),
    sa.PrimaryKeyConstraint('database_id'),
    sa.UniqueConstraint('database_id')
    )
    op.create_table('media',
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('media_url', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.Column('date_updated', sa.Date(), nullable=True),
    sa.Column('realitem_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['realitem_id'], ['real_items.database_id'], ),
    sa.PrimaryKeyConstraint('database_id'),
    sa.UniqueConstraint('database_id')
    )
    op.create_table('offers_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scryfall_card_id', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('merchant', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('card_type', sa.String(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('offers_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['condition'], ['conditions.us_code'], ),
    sa.ForeignKeyConstraint(['merchant'], ['merchants.shortcode'], ),
    sa.ForeignKeyConstraint(['offers_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('real_items_defects',
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('defect_name', sa.String(), nullable=True),
    sa.Column('realitem_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['realitem_id'], ['real_items.database_id'], ),
    sa.PrimaryKeyConstraint('database_id'),
    sa.UniqueConstraint('database_id')
    )
    op.create_table('subscriptions',
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('subscriberId', sa.Integer(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('offersId', sa.Integer(), nullable=True),
    sa.Column('realItemId', sa.Integer(), nullable=True),
    sa.Column('collectionId', sa.Integer(), nullable=True),
    sa.Column('genericItemId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collectionId'], ['item_collections.database_id'], ),
    sa.ForeignKeyConstraint(['genericItemId'], ['generic_items.id'], ),
    sa.ForeignKeyConstraint(['offersId'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['realItemId'], ['real_items.database_id'], ),
    sa.ForeignKeyConstraint(['subscriberId'], ['users.database_id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.database_id'], ),
    sa.PrimaryKeyConstraint('database_id')
    )
    op.create_table('trade_items',
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('real_item_id', sa.Integer(), nullable=True),
    sa.Column('side', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['real_item_id'], ['real_items.database_id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.database_id'], ),
    sa.PrimaryKeyConstraint('database_id')
    )
    op.create_table('transaction_items',
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('real_item_id', sa.Integer(), nullable=True),
    sa.Column('side', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['real_item_id'], ['real_items.database_id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.database_id'], ),
    sa.PrimaryKeyConstraint('database_id')
    )
    op.create_table('user_list_items',
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('real_item_id', sa.Integer(), nullable=True),
    sa.Column('user_list_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['real_item_id'], ['real_items.database_id'], ),
    sa.ForeignKeyConstraint(['user_list_id'], ['user_lists.database_id'], ),
    sa.PrimaryKeyConstraint('database_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_list_items')
    op.drop_table('transaction_items')
    op.drop_table('trade_items')
    op.drop_table('subscriptions')
    op.drop_table('real_items_defects')
    op.drop_table('offers_history')
    op.drop_table('media')
    op.drop_table('latest_offers_history')
    op.drop_table('activities')
    op.drop_table('real_items')
    op.drop_table('offers')
    op.drop_table('latest_offers')
    op.drop_table('collection_history')
    op.drop_table('user_lists')
    op.drop_table('transactions')
    op.drop_table('trades')
    op.drop_table('notifications')
    op.drop_table('merchants_condition_multiplier')
    op.drop_table('item_collections')
    op.drop_table('generic_items')
    op.drop_table('users')
    op.drop_table('transaction_status')
    op.drop_table('trade_status')
    op.drop_table('topics')
    op.drop_table('sets')
    op.drop_table('merchants')
    op.drop_table('conditions')
    # ### end Alembic commands ###
