"""empty message

Revision ID: a5a921d08eb4
Revises: 44d841bdeaa5
Create Date: 2021-09-11 11:25:33.067948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5a921d08eb4'
down_revision = '44d841bdeaa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conditions', sa.Column('us_code', sa.String(), nullable=True))
    op.add_column('conditions', sa.Column('eu_code', sa.String(), nullable=True))
    op.add_column('conditions', sa.Column('type', sa.String(), nullable=True))
    op.drop_constraint('conditions_short_code_key', 'conditions', type_='unique')
    op.drop_column('conditions', 'eu_name')
    op.drop_column('conditions', 'short_code')
    op.drop_column('conditions', 'us_name')
    op.create_unique_constraint(None, 'merchants_condition_multiplier', ['database_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'merchants_condition_multiplier', type_='unique')
    op.add_column('conditions', sa.Column('us_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('conditions', sa.Column('short_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('conditions', sa.Column('eu_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('conditions_short_code_key', 'conditions', ['short_code'])
    op.drop_column('conditions', 'type')
    op.drop_column('conditions', 'eu_code')
    op.drop_column('conditions', 'us_code')
    # ### end Alembic commands ###
