"""empty message

Revision ID: af39be313a27
Revises: 808a31f10770
Create Date: 2021-08-22 11:29:42.728068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af39be313a27'
down_revision = '808a31f10770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers_history', sa.Column('offer_id', sa.Integer(), nullable=True))
    op.drop_constraint('offers_history_offer_fkey', 'offers_history', type_='foreignkey')
    op.create_foreign_key(None, 'offers_history', 'offers', ['offer_id'], ['id'])
    op.drop_column('offers_history', 'offer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers_history', sa.Column('offer', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'offers_history', type_='foreignkey')
    op.create_foreign_key('offers_history_offer_fkey', 'offers_history', 'offers', ['offer'], ['id'])
    op.drop_column('offers_history', 'offer_id')
    # ### end Alembic commands ###
