"""empty message

Revision ID: b10ed0228346
Revises: 8b8a2b491aec
Create Date: 2021-09-11 12:53:22.177609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b10ed0228346'
down_revision = '8b8a2b491aec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offers_history', 'condition',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint('offers_history_condition_fkey', 'offers_history', type_='foreignkey')
    op.drop_column('offers_history', 'condition_string')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers_history', sa.Column('condition_string', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('offers_history_condition_fkey', 'offers_history', 'conditions', ['condition'], ['database_id'])
    op.alter_column('offers_history', 'condition',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
