"""empty message

Revision ID: b3dce92b6a61
Revises: cf97ebd7e297
Create Date: 2021-09-11 15:39:48.954780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3dce92b6a61'
down_revision = 'cf97ebd7e297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('shortcode', sa.String(), nullable=False))
    op.drop_constraint('merchants_short_code_key', 'merchants', type_='unique')
    op.create_unique_constraint(None, 'merchants', ['shortcode'])
    op.drop_column('merchants', 'short_code')
    op.drop_constraint('merchants_condition_multiplier_merchant_fkey', 'merchants_condition_multiplier', type_='foreignkey')
    op.create_foreign_key(None, 'merchants_condition_multiplier', 'merchants', ['merchant'], ['shortcode'])
    op.add_column('offers_history', sa.Column('merchant', sa.String(), nullable=True))
    op.create_foreign_key(None, 'offers_history', 'merchants', ['merchant'], ['shortcode'])
    op.drop_column('offers_history', 'merchant_string')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers_history', sa.Column('merchant_string', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'offers_history', type_='foreignkey')
    op.drop_column('offers_history', 'merchant')
    op.drop_constraint(None, 'merchants_condition_multiplier', type_='foreignkey')
    op.create_foreign_key('merchants_condition_multiplier_merchant_fkey', 'merchants_condition_multiplier', 'merchants', ['merchant'], ['short_code'])
    op.add_column('merchants', sa.Column('short_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'merchants', type_='unique')
    op.create_unique_constraint('merchants_short_code_key', 'merchants', ['short_code'])
    op.drop_column('merchants', 'shortcode')
    # ### end Alembic commands ###
