"""empty message

Revision ID: b6347bb32cfa
Revises: b2e29b1d48a4
Create Date: 2021-12-02 10:51:56.029145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6347bb32cfa'
down_revision = 'b2e29b1d48a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('real_items', sa.Column('user_list', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('real_items', 'user_list')
    # ### end Alembic commands ###
