"""empty message

Revision ID: bacb76dabfeb
Revises: b10ed0228346
Create Date: 2021-09-11 12:53:57.717380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bacb76dabfeb'
down_revision = 'b10ed0228346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('offers_history_condition_fkey', 'offers_history', type_='foreignkey')
    op.drop_column('offers_history', 'condition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers_history', sa.Column('condition', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('offers_history_condition_fkey', 'offers_history', 'conditions', ['condition'], ['database_id'])
    # ### end Alembic commands ###
