"""empty message

Revision ID: bcb1348e69c4
Revises: 6bd21f4d1ff9
Create Date: 2021-10-06 12:09:46.032632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcb1348e69c4'
down_revision = '6bd21f4d1ff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('item_collections_name_key', 'item_collections', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('item_collections_name_key', 'item_collections', ['name'])
    # ### end Alembic commands ###
