"""empty message

Revision ID: bfc4112b9a2a
Revises: bf61ace8de7e
Create Date: 2021-12-08 13:33:17.080265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfc4112b9a2a'
down_revision = 'bf61ace8de7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_status',
    sa.Column('state', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('state')
    )
    op.create_table('transactions',
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.Column('date_updated', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('left_credit', sa.Float(), nullable=True),
    sa.Column('left_owner', sa.Integer(), nullable=True),
    sa.Column('left_confirm', sa.Boolean(), nullable=True),
    sa.Column('right_credit', sa.Float(), nullable=True),
    sa.Column('right_owner', sa.Integer(), nullable=True),
    sa.Column('right_confirm', sa.Boolean(), nullable=True),
    sa.Column('left_close', sa.Boolean(), nullable=True),
    sa.Column('right_close', sa.Boolean(), nullable=True),
    sa.Column('half_closed_side', sa.String(), nullable=True),
    sa.Column('paypal_costs', sa.Float(), nullable=True),
    sa.Column('shipping_and_handling_costs', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['left_owner'], ['users.database_id'], ),
    sa.ForeignKeyConstraint(['right_owner'], ['users.database_id'], ),
    sa.ForeignKeyConstraint(['status'], ['transaction_status.state'], ),
    sa.PrimaryKeyConstraint('database_id')
    )
    op.create_table('transaction_items',
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('real_item_id', sa.Integer(), nullable=True),
    sa.Column('side', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['real_item_id'], ['real_items.database_id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.database_id'], ),
    sa.PrimaryKeyConstraint('database_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_items')
    op.drop_table('transactions')
    op.drop_table('transaction_status')
    # ### end Alembic commands ###
