"""empty message

Revision ID: c465ed484eeb
Revises: 679f5ddbc285
Create Date: 2021-09-12 10:19:51.181643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c465ed484eeb'
down_revision = '679f5ddbc285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'conditions', ['us_code'])
    op.alter_column('merchants_condition_multiplier', 'condition_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_foreign_key(None, 'merchants_condition_multiplier', 'conditions', ['condition_id'], ['us_code'])
    op.add_column('offers_history', sa.Column('condition', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'offers_history', 'conditions', ['condition'], ['us_code'])
    op.drop_column('offers_history', 'condition_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers_history', sa.Column('condition_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'offers_history', type_='foreignkey')
    op.drop_column('offers_history', 'condition')
    op.drop_constraint(None, 'merchants_condition_multiplier', type_='foreignkey')
    op.alter_column('merchants_condition_multiplier', 'condition_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_constraint(None, 'conditions', type_='unique')
    # ### end Alembic commands ###
