"""empty message

Revision ID: c48800f95b81
Revises: 091b10dba542
Create Date: 2021-08-23 13:58:05.273013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c48800f95b81'
down_revision = '091b10dba542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'item_index',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('offers', sa.Column('item_index', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'offers', ['item_index'])
    op.create_foreign_key(None, 'offers', 'items', ['scryfall_card_id'], ['scryfall_card_id'])
    op.create_foreign_key(None, 'offers', 'items', ['item_index'], ['item_index'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offers', type_='foreignkey')
    op.drop_constraint(None, 'offers', type_='foreignkey')
    op.drop_constraint(None, 'offers', type_='unique')
    op.drop_column('offers', 'item_index')
    op.alter_column('items', 'item_index',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
