"""empty message

Revision ID: c7a58424bfc4
Revises: 6f04d9835884
Create Date: 2021-08-20 21:32:17.114129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7a58424bfc4'
down_revision = '6f04d9835884'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_amount', sa.Float(), nullable=True),
    sa.Column('offer_type', sa.String(), nullable=True),
    sa.Column('last_updated', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('offer_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant', sa.String(), nullable=True),
    sa.Column('offer_amount', sa.Float(), nullable=True),
    sa.Column('item_type', sa.String(), nullable=True),
    sa.Column('inserted_at', sa.Date(), nullable=True),
    sa.Column('current_offers_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['current_offers_id'], ['current_offers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offer_history')
    op.drop_table('current_offers')
    # ### end Alembic commands ###
