"""empty message

Revision ID: cc20bbca573c
Revises: 
Create Date: 2021-09-03 16:12:57.328134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc20bbca573c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'conditions', ['database_id'])
    op.create_unique_constraint(None, 'generic_items', ['id'])
    op.create_unique_constraint(None, 'item_collections', ['database_id'])
    op.create_unique_constraint(None, 'merchants', ['database_id'])
    op.create_unique_constraint(None, 'offers', ['id'])
    op.create_unique_constraint(None, 'offers_history', ['id'])
    op.create_unique_constraint(None, 'real_items', ['database_id'])
    op.create_unique_constraint(None, 'sets', ['id'])
    op.create_unique_constraint(None, 'users', ['database_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'sets', type_='unique')
    op.drop_constraint(None, 'real_items', type_='unique')
    op.drop_constraint(None, 'offers_history', type_='unique')
    op.drop_constraint(None, 'offers', type_='unique')
    op.drop_constraint(None, 'merchants', type_='unique')
    op.drop_constraint(None, 'item_collections', type_='unique')
    op.drop_constraint(None, 'generic_items', type_='unique')
    op.drop_constraint(None, 'conditions', type_='unique')
    # ### end Alembic commands ###
