"""empty message

Revision ID: cca66701671f
Revises: 5289763224f9
Create Date: 2022-01-25 01:35:34.909693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cca66701671f'
down_revision = '5289763224f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'listing_feedback', ['database_id'])
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login')
    op.drop_constraint(None, 'listing_feedback', type_='unique')
    # ### end Alembic commands ###
