"""empty message

Revision ID: cd9b7bb679ef
Revises: a5a921d08eb4
Create Date: 2021-09-11 12:15:18.230680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd9b7bb679ef'
down_revision = 'a5a921d08eb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conditions', sa.Column('sort_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conditions', 'sort_order')
    # ### end Alembic commands ###
