"""empty message

Revision ID: ceb840c96dc4
Revises: 335d8ad044fd
Create Date: 2021-10-20 11:37:24.887973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceb840c96dc4'
down_revision = '335d8ad044fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'latest_offers', ['database_id'])
    op.add_column('latest_offers_history', sa.Column('database_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'latest_offers_history', ['database_id'])
    op.drop_column('latest_offers_history', 'databaseId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('latest_offers_history', sa.Column('databaseId', sa.INTEGER(), server_default=sa.text('nextval(\'"latest_offers_history_databaseId_seq"\'::regclass)'), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'latest_offers_history', type_='unique')
    op.drop_column('latest_offers_history', 'database_id')
    op.drop_constraint(None, 'latest_offers', type_='unique')
    # ### end Alembic commands ###
