"""empty message

Revision ID: cf97ebd7e297
Revises: fcecebb5f9e6
Create Date: 2021-09-11 15:24:16.574184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf97ebd7e297'
down_revision = 'fcecebb5f9e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers_history', sa.Column('merchant_string', sa.String(), nullable=True))
    op.drop_column('offers_history', 'merchant')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers_history', sa.Column('merchant', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('offers_history', 'merchant_string')
    # ### end Alembic commands ###
