"""empty message

Revision ID: d03abd2c0829
Revises: 33a060e89670
Create Date: 2021-08-20 12:07:49.346511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd03abd2c0829'
down_revision = '33a060e89670'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('scryfall_set_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'cards', 'sets', ['scryfall_set_id'], ['scryfall_set_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_column('cards', 'scryfall_set_id')
    # ### end Alembic commands ###
