"""empty message

Revision ID: d50cb1553ce7
Revises: c48800f95b81
Create Date: 2021-08-23 14:00:46.452779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd50cb1553ce7'
down_revision = 'c48800f95b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('item_index', sa.String(), nullable=True))
    op.add_column('offers', sa.Column('item_id', sa.Integer(), nullable=True))
    op.drop_constraint('offers_items_id_fkey', 'offers', type_='foreignkey')
    op.create_foreign_key(None, 'offers', 'items', ['item_id'], ['id'])
    op.drop_column('offers', 'items_id')
    op.add_column('offers_history', sa.Column('scryfall_card_id', sa.String(), nullable=True))
    op.add_column('offers_history', sa.Column('offer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'offers_history', 'offers', ['offer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offers_history', type_='foreignkey')
    op.drop_column('offers_history', 'offer_id')
    op.drop_column('offers_history', 'scryfall_card_id')
    op.add_column('offers', sa.Column('items_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'offers', type_='foreignkey')
    op.create_foreign_key('offers_items_id_fkey', 'offers', 'items', ['items_id'], ['id'])
    op.drop_column('offers', 'item_id')
    op.drop_column('offers', 'item_index')
    # ### end Alembic commands ###
