"""empty message

Revision ID: d9d281111154
Revises: 655cd9d1338b
Create Date: 2021-09-11 09:10:15.987235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9d281111154'
down_revision = '655cd9d1338b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('generator', sa.String(), nullable=True),
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('object', sa.String(), nullable=True),
    sa.Column('published', sa.Date(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('updated', sa.Date(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('verb', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('database_id'),
    sa.UniqueConstraint('database_id')
    )
    op.create_table('topics',
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('database_id'),
    sa.UniqueConstraint('database_id')
    )
    op.add_column('conditions', sa.Column('display_name', sa.String(), nullable=True))
    op.add_column('conditions', sa.Column('trade_in_multiplier', sa.Float(), nullable=True))
    op.add_column('conditions', sa.Column('selling_multiplier', sa.Float(), nullable=True))
    op.add_column('conditions', sa.Column('date_updated', sa.Date(), nullable=True))
    op.drop_column('conditions', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conditions', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('conditions', 'date_updated')
    op.drop_column('conditions', 'selling_multiplier')
    op.drop_column('conditions', 'trade_in_multiplier')
    op.drop_column('conditions', 'display_name')
    op.drop_table('topics')
    op.drop_table('activity')
    # ### end Alembic commands ###
