"""empty message

Revision ID: de6eb862bd6f
Revises: 0885d01cb642
Create Date: 2021-08-20 11:21:58.484767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de6eb862bd6f'
down_revision = '0885d01cb642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('image_uri_small', sa.Boolean(), nullable=True))
    op.add_column('cards', sa.Column('image_uri_normal', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('image_uri_large', sa.Date(), nullable=True))
    op.add_column('cards', sa.Column('image_uri_png', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'image_uri_png')
    op.drop_column('cards', 'image_uri_large')
    op.drop_column('cards', 'image_uri_normal')
    op.drop_column('cards', 'image_uri_small')
    # ### end Alembic commands ###
