"""empty message

Revision ID: e374a8bd66cb
Revises: 2edc93bcb35f
Create Date: 2021-09-09 10:16:29.945959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e374a8bd66cb'
down_revision = '2edc93bcb35f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('real_items', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'real_items', 'users', ['user_id'], ['database_id'])
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'real_items', type_='foreignkey')
    op.drop_column('real_items', 'user_id')
    # ### end Alembic commands ###
