"""empty message

Revision ID: e52f3736a873
Revises: 8458dc4eaabd
Create Date: 2021-09-29 00:19:33.800527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e52f3736a873'
down_revision = '8458dc4eaabd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'activities', ['database_id'])
    op.drop_constraint('activities_realItemId_fkey', 'activities', type_='foreignkey')
    op.drop_constraint('activities_collectionId_fkey', 'activities', type_='foreignkey')
    op.drop_constraint('activities_userId_fkey', 'activities', type_='foreignkey')
    op.drop_constraint('activities_genericItemId_fkey', 'activities', type_='foreignkey')
    op.drop_constraint('activities_offersId_fkey', 'activities', type_='foreignkey')
    op.create_foreign_key(None, 'activities', 'offers', ['offersId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'activities', 'item_collections', ['collectionId'], ['database_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'activities', 'users', ['userId'], ['database_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'activities', 'real_items', ['realItemId'], ['database_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'activities', 'generic_items', ['genericItemId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.create_foreign_key('activities_offersId_fkey', 'activities', 'offers', ['offersId'], ['id'])
    op.create_foreign_key('activities_genericItemId_fkey', 'activities', 'generic_items', ['genericItemId'], ['id'])
    op.create_foreign_key('activities_userId_fkey', 'activities', 'users', ['userId'], ['database_id'])
    op.create_foreign_key('activities_collectionId_fkey', 'activities', 'item_collections', ['collectionId'], ['database_id'])
    op.create_foreign_key('activities_realItemId_fkey', 'activities', 'real_items', ['realItemId'], ['database_id'])
    op.drop_constraint(None, 'activities', type_='unique')
    # ### end Alembic commands ###
