"""empty message

Revision ID: ec0cedba96f5
Revises: 3dbd7b9987c2
Create Date: 2021-08-22 11:25:12.660352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec0cedba96f5'
down_revision = '3dbd7b9987c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'offers', ['id'])
    op.create_unique_constraint(None, 'offers_history', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offers_history', type_='unique')
    op.drop_constraint(None, 'offers', type_='unique')
    # ### end Alembic commands ###
