"""empty message

Revision ID: f1619639e22f
Revises: 4aae462fbdd3
Create Date: 2021-12-14 16:39:15.242410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1619639e22f'
down_revision = '4aae462fbdd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('admin_comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'admin_comment')
    # ### end Alembic commands ###
