"""empty message

Revision ID: f33dadfb4517
Revises: 06a6ab87d144
Create Date: 2021-08-20 12:18:39.417579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f33dadfb4517'
down_revision = '06a6ab87d144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'set_uri',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'cards', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cards', type_='unique')
    op.alter_column('cards', 'set_uri',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
