"""empty message

Revision ID: f50918a53f66
Revises: f9dd96778079
Create Date: 2021-08-20 10:23:01.896476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f50918a53f66'
down_revision = 'f9dd96778079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scryfall_set_id', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('mtgo_code', sa.String(), nullable=True),
    sa.Column('arena_code', sa.String(), nullable=True),
    sa.Column('tcgplayer_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('uri', sa.String(), nullable=True),
    sa.Column('scryfall_uri', sa.String(), nullable=True),
    sa.Column('search_uri', sa.String(), nullable=True),
    sa.Column('released_at', sa.Date(), nullable=True),
    sa.Column('set_type', sa.String(), nullable=True),
    sa.Column('digital', sa.Boolean(), nullable=True),
    sa.Column('nonfoil_only', sa.Boolean(), nullable=True),
    sa.Column('foil_only', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sets')
    # ### end Alembic commands ###
