"""empty message

Revision ID: f85bafa9e6a8
Revises: bcb1348e69c4
Create Date: 2021-10-15 15:56:21.752123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f85bafa9e6a8'
down_revision = 'bcb1348e69c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_history',
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('collectionId', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Date(), nullable=True),
    sa.Column('retail_value', sa.Float(), nullable=True),
    sa.Column('pm_value', sa.Float(), nullable=True),
    sa.Column('number_of_items', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collectionId'], ['item_collections.database_id'], ),
    sa.PrimaryKeyConstraint('database_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection_history')
    # ### end Alembic commands ###
