"""empty message

Revision ID: f9dd96778079
Revises: 3ddf5acfe187
Create Date: 2021-08-20 09:49:32.185710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9dd96778079'
down_revision = '3ddf5acfe187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('sets', 'object')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sets', sa.Column('object', sa.VARCHAR(length=25), autoincrement=False, nullable=True))
    op.drop_table('cards')
    # ### end Alembic commands ###
