"""empty message

Revision ID: fb10a19b7d1d
Revises: dc0b04d88ea0
Create Date: 2021-08-20 11:53:11.852463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb10a19b7d1d'
down_revision = 'dc0b04d88ea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'scryfall_set_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('scryfall_set_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
