"""empty message

Revision ID: fc02b51ddd04
Revises: 925cb5c84e29
Create Date: 2021-12-30 13:14:04.419579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc02b51ddd04'
down_revision = '925cb5c84e29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_lists',
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.database_id'], ),
    sa.PrimaryKeyConstraint('database_id'),
    sa.UniqueConstraint('database_id')
    )
    op.add_column('real_items', sa.Column('item_list_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'real_items', 'item_lists', ['item_list_id'], ['database_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'real_items', type_='foreignkey')
    op.drop_column('real_items', 'item_list_id')
    op.drop_table('item_lists')
    # ### end Alembic commands ###
