"""empty message

Revision ID: fcecebb5f9e6
Revises: 067a780087c5
Create Date: 2021-09-11 15:21:18.689886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcecebb5f9e6'
down_revision = '067a780087c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'merchants', ['short_code'])
    op.add_column('merchants_condition_multiplier', sa.Column('merchant', sa.String(), nullable=True))
    op.create_foreign_key(None, 'merchants_condition_multiplier', 'merchants', ['merchant'], ['short_code'])
    op.drop_column('merchants_condition_multiplier', 'merchant_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants_condition_multiplier', sa.Column('merchant_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'merchants_condition_multiplier', type_='foreignkey')
    op.drop_column('merchants_condition_multiplier', 'merchant')
    op.drop_constraint(None, 'merchants', type_='unique')
    # ### end Alembic commands ###
