"""empty message

Revision ID: fffd372929a6
Revises: 78f9ab674b29
Create Date: 2021-08-20 10:54:00.417058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fffd372929a6'
down_revision = '78f9ab674b29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sets', sa.Column('icon_svg_uri', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'sets', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sets', type_='unique')
    op.drop_column('sets', 'icon_svg_uri')
    # ### end Alembic commands ###
